<a href="https://colab.research.google.com/github/Somesh140/Pytorch-basics/blob/main/PytorchLinearRegression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!nvidia-smi

Tue Jun 20 13:15:34 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   39C    P8     9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
import numpy as np
import torch

In [ ]:
#Input data
input = np.array([[32,55,77],
                  [31,75,57],
                  [52,55,77],
                  [22,100,87],
                  [62,80,77]], dtype = 'float32' )
input

array([[ 32.,  55.,  77.],
       [ 31.,  75.,  57.],
       [ 52.,  55.,  77.],
       [ 22., 100.,  87.],
       [ 62.,  80.,  77.]], dtype=float32)

In [ ]:
# target
target = np.array([[32,66],
                   [52,76],
                   [102,55],
                   [32,26],
                   [99,100]
                   ],dtype='float32')
target

array([[ 32.,  66.],
       [ 52.,  76.],
       [102.,  55.],
       [ 32.,  26.],
       [ 99., 100.]], dtype=float32)

In [ ]:
inputs = torch.from_numpy(input)
targets = torch.from_numpy(target)
print(inputs,targets)

tensor([[ 32.,  55.,  77.],
        [ 31.,  75.,  57.],
        [ 52.,  55.,  77.],
        [ 22., 100.,  87.],
        [ 62.,  80.,  77.]]) tensor([[ 32.,  66.],
        [ 52.,  76.],
        [102.,  55.],
        [ 32.,  26.],
        [ 99., 100.]])


In [ ]:
# weights and biases
w = torch.randn(2,3, requires_grad = True) # 2 output column and 3 input columns
b = torch.randn(2, requires_grad= True) # 2 output columns

print(w)
print(b)

tensor([[-0.1278,  0.9046,  0.4064],
        [-2.0081, -0.7997,  0.9862]], requires_grad=True)
tensor([-0.3955, -0.1073], requires_grad=True)


In [ ]:
def model(x):
  return x@w.t() + b

In [ ]:
preds = model(inputs)
print(preds)

tensor([[  76.5648,  -32.4067],
        [  86.6561,  -66.1174],
        [  74.0091,  -72.5678],
        [ 122.6146,  -38.4496],
        [  95.3466, -112.6405]], grad_fn=<AddBackward0>)


In [ ]:
targets

tensor([[ 32.,  66.],
        [ 52.,  76.],
        [102.,  55.],
        [ 32.,  26.],
        [ 99., 100.]])

In [ ]:
# loss
def MSE(t1,t2):
  diff = t1 -t2
  return torch.sum(diff*diff)/diff.numel()

In [ ]:
# compute loss
loss = MSE(preds, targets)
print(loss)

tensor(10771.9434, grad_fn=<DivBackward0>)


In [ ]:
# Compute gradient
loss.backward()

In [ ]:
print(w)
print(w.grad)

tensor([[-0.1278,  0.9046,  0.4064],
        [-2.0081, -0.7997,  0.9862]], requires_grad=True)
tensor([[  562.3798,  2455.9924,  2170.7498],
        [-5757.9565, -9308.7207, -9496.2324]])


In [ ]:
with torch.no_grad(): # no_grad to disable gradient calculation
  w -= w.grad * 1e-5
  b -= b.grad * 1e-5

In [ ]:
print(w)

tensor([[-0.1334,  0.8801,  0.3847],
        [-1.9505, -0.7066,  1.0812]], requires_grad=True)


In [ ]:
preds = model(inputs)

In [ ]:
loss = MSE(preds, targets)
print(loss)

tensor(8701.4629, grad_fn=<DivBackward0>)


In [ ]:
# Training
n = 400
for i in range(n):
  preds = model(inputs)
  loss = MSE(preds, targets)
  loss.backward()
  with torch.no_grad(): # no_grad to disable gradient calculation
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5

  w.grad.zero_() # to clear the previous gradient values
  b.grad.zero_()

  print(f"EPOCHS: {i}/{n}---------Loss: {loss}")

EPOCHS: 0/400---------Loss: 1327.6907958984375
EPOCHS: 1/400---------Loss: 1322.6842041015625
EPOCHS: 2/400---------Loss: 1317.705078125
EPOCHS: 3/400---------Loss: 1312.752685546875
EPOCHS: 4/400---------Loss: 1307.8275146484375
EPOCHS: 5/400---------Loss: 1302.9290771484375
EPOCHS: 6/400---------Loss: 1298.0570068359375
EPOCHS: 7/400---------Loss: 1293.211669921875
EPOCHS: 8/400---------Loss: 1288.3924560546875
EPOCHS: 9/400---------Loss: 1283.599365234375
EPOCHS: 10/400---------Loss: 1278.832275390625
EPOCHS: 11/400---------Loss: 1274.0911865234375
EPOCHS: 12/400---------Loss: 1269.375732421875
EPOCHS: 13/400---------Loss: 1264.6856689453125
EPOCHS: 14/400---------Loss: 1260.021240234375
EPOCHS: 15/400---------Loss: 1255.3814697265625
EPOCHS: 16/400---------Loss: 1250.7672119140625
EPOCHS: 17/400---------Loss: 1246.177490234375
EPOCHS: 18/400---------Loss: 1241.6129150390625
EPOCHS: 19/400---------Loss: 1237.0728759765625
EPOCHS: 20/400---------Loss: 1232.5572509765625
EPOCHS: 21/40

In [ ]:
preds = model(inputs)
preds

tensor([[53.1036, 68.9289],
        [49.1375, 42.1784],
        [80.1249, 75.3134],
        [40.9827, 61.0539],
        [93.6729, 70.3700]], grad_fn=<AddBackward0>)

In [ ]:
targets

tensor([[ 32.,  66.],
        [ 52.,  76.],
        [102.,  55.],
        [ 32.,  26.],
        [ 99., 100.]])

# Using Torch built in function


In [ ]:
# Using Torch built in function
import torch.nn as nn
import numpy as np


In [ ]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43],
                   [91, 88, 64],
                   [87, 134, 58],
                   [102, 43, 37],
                   [69, 96, 70],
                   [74, 66, 43],
                   [91, 87, 65],
                   [88, 134, 59],
                   [101, 44, 37],
                   [68, 96, 71],
                   [73, 66, 44],
                   [92, 87, 64],
                   [87, 135, 57],
                   [103, 43, 36],
                   [68, 97, 70]],
                  dtype='float32')

# Targets (apples, oranges)
targets = np.array([[56, 70],
                    [81, 101],
                    [119, 133],
                    [22, 37],
                    [103, 119],
                    [57, 69],
                    [80, 102],
                    [118, 132],
                    [21, 38],
                    [104, 118],
                    [57, 69],
                    [82, 100],
                    [118, 134],
                    [20, 38],
                    [102, 120]],
                   dtype='float32')

inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)


In [ ]:
inputs

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 74.,  66.,  43.],
        [ 91.,  87.,  65.],
        [ 88., 134.,  59.],
        [101.,  44.,  37.],
        [ 68.,  96.,  71.],
        [ 73.,  66.,  44.],
        [ 92.,  87.,  64.],
        [ 87., 135.,  57.],
        [103.,  43.,  36.],
        [ 68.,  97.,  70.]])

We are using 15 training examples to illustrate how to work with large datasets in small batches.

# Dataset and DataLoader
We'll create a TensorDataset, which allows access to rows from inputs and targets as tuples, and provides standard APIs for working with many different types of datasets in PyTorch.

In [ ]:
from torch.utils.data import TensorDataset

In [ ]:
# Define dataset
train_ds = TensorDataset(inputs, targets)
train_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]),
 tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

The TensorDataset allows us to access a small section of the training data using the array indexing notation ([0:3] in the above code). It returns a tuple with two elements. The first element contains the input variables for the selected rows, and the second contains the targets.

We'll also create a DataLoader, which can split the data into batches of a predefined size while training. It also provides other utilities like shuffling and random sampling of the data.

In [ ]:
from torch.utils.data import DataLoader

In [ ]:
# Define data loader
batch_size = 5
train_dl = DataLoader(train_ds, batch_size, shuffle=True)

We can use the data loader in a for loop. Let's look at an example.

In [ ]:
for xb, yb in train_dl:
    print(xb)
    print(yb)
    break

tensor([[ 87., 135.,  57.],
        [ 73.,  67.,  43.],
        [ 69.,  96.,  70.],
        [ 73.,  66.,  44.],
        [ 91.,  87.,  65.]])
tensor([[118., 134.],
        [ 56.,  70.],
        [103., 119.],
        [ 57.,  69.],
        [ 80., 102.]])


In each iteration, the data loader returns one batch of data with the given batch size. If shuffle is set to True, it shuffles the training data before creating batches. Shuffling helps randomize the input to the optimization algorithm, leading to a faster reduction in the loss.

#nn.Linear
Instead of initializing the weights & biases manually, we can define the model using the nn.Linear class from PyTorch, which does it automatically.

In [ ]:
#nn.Linear
# Define model
model = nn.Linear(3, 2) # 3 features 2 outputs
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[-0.0244,  0.1924, -0.4866],
        [ 0.4739, -0.2806, -0.1876]], requires_grad=True)
Parameter containing:
tensor([ 0.1623, -0.1380], requires_grad=True)


PyTorch models also have a helpful .parameters method, which returns a list containing all the weights and bias matrices present in the model. For our linear regression model, we have one weight matrix and one bias matrix.

In [ ]:
# Parameters
list(model.parameters())

[Parameter containing:
 tensor([[-0.0244,  0.1924, -0.4866],
         [ 0.4739, -0.2806, -0.1876]], requires_grad=True),
 Parameter containing:
 tensor([ 0.1623, -0.1380], requires_grad=True)]

In [ ]:
# Generate predictions
preds = model(inputs)
preds

tensor([[ -9.6546,   7.5915],
        [-16.2731,   6.2901],
        [ -4.4067,  -7.3883],
        [-12.0591,  29.1954],
        [-17.1173,  -7.5065],
        [ -9.8714,   8.3460],
        [-16.9522,   6.3832],
        [ -4.9177,  -7.1020],
        [-11.8424,  28.4408],
        [-17.5796,  -8.1679],
        [-10.3336,   7.6845],
        [-16.4899,   7.0447],
        [ -3.7277,  -7.4814],
        [-11.5969,  29.8569],
        [-16.9006,  -8.2610]], grad_fn=<AddmmBackward0>)

Loss Function
Instead of defining a loss function manually, we can use the built-in loss function mse_loss.

In [ ]:
import torch.nn.functional as F

The nn.functional package contains many useful loss functions and several other utilities.

In [ ]:
# Define loss function
loss_fn = F.mse_loss

In [ ]:
loss = loss_fn(model(inputs), targets)
print(loss)

tensor(9312.3789, grad_fn=<MseLossBackward0>)


#Optimizer
Instead of manually manipulating the model's weights & biases using gradients, we can use the optimizer optim.SGD. SGD is short for "stochastic gradient descent". The term stochastic indicates that samples are selected in random batches instead of as a single group.

In [ ]:
# optimizer
opt = torch.optim.SGD(model.parameters(), lr = 1e-5)