<a href="https://colab.research.google.com/github/Somesh140/Pytorch-basics/blob/main/PytorchLinearRegression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!nvidia-smi

Wed Jun 21 05:26:04 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   56C    P8    10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [2]:
import numpy as np
import torch

In [3]:
#Input data
input = np.array([[32,55,77],
                  [31,75,57],
                  [52,55,77],
                  [22,100,87],
                  [62,80,77]], dtype = 'float32' )
input

array([[ 32.,  55.,  77.],
       [ 31.,  75.,  57.],
       [ 52.,  55.,  77.],
       [ 22., 100.,  87.],
       [ 62.,  80.,  77.]], dtype=float32)

In [4]:
# target
target = np.array([[32,66],
                   [52,76],
                   [102,55],
                   [32,26],
                   [99,100]
                   ],dtype='float32')
target

array([[ 32.,  66.],
       [ 52.,  76.],
       [102.,  55.],
       [ 32.,  26.],
       [ 99., 100.]], dtype=float32)

In [5]:
inputs = torch.from_numpy(input)
targets = torch.from_numpy(target)
print(inputs,targets)

tensor([[ 32.,  55.,  77.],
        [ 31.,  75.,  57.],
        [ 52.,  55.,  77.],
        [ 22., 100.,  87.],
        [ 62.,  80.,  77.]]) tensor([[ 32.,  66.],
        [ 52.,  76.],
        [102.,  55.],
        [ 32.,  26.],
        [ 99., 100.]])


In [6]:
# weights and biases
w = torch.randn(2,3, requires_grad = True) # 2 output column and 3 input columns
b = torch.randn(2, requires_grad= True) # 2 output columns

print(w)
print(b)

tensor([[ 1.8602,  0.2943, -0.9972],
        [-0.3848,  0.2942,  1.5551]], requires_grad=True)
tensor([-1.2363,  1.2772], requires_grad=True)


In [7]:
def model(x):
  return x@w.t() + b

In [8]:
preds = model(inputs)
print(preds)

tensor([[ -2.3052, 124.8861],
        [ 21.6648, 100.0537],
        [ 34.8984, 117.1894],
        [-17.6340, 157.5252],
        [ 60.8585, 120.6966]], grad_fn=<AddBackward0>)


In [9]:
targets

tensor([[ 32.,  66.],
        [ 52.,  76.],
        [102.,  55.],
        [ 32.,  26.],
        [ 99., 100.]])

In [10]:
# loss
def MSE(t1,t2):
  diff = t1 -t2
  return torch.sum(diff*diff)/diff.numel()

In [11]:
# compute loss
loss = MSE(preds, targets)
print(loss)

tensor(3615.8906, grad_fn=<DivBackward0>)


In [12]:
# Compute gradient
loss.backward()

In [13]:
print(w)
print(w.grad)

tensor([[ 1.8602,  0.2943, -0.9972],
        [-0.3848,  0.2942,  1.5551]], requires_grad=True)
tensor([[-1796.8325, -3173.4463, -3358.4963],
        [ 2008.1223,  4654.2852,  4746.0410]])


In [14]:
with torch.no_grad(): # no_grad to disable gradient calculation
  w -= w.grad * 1e-5
  b -= b.grad * 1e-5

In [15]:
print(w)

tensor([[ 1.8781,  0.3261, -0.9636],
        [-0.4049,  0.2477,  1.5076]], requires_grad=True)


In [16]:
preds = model(inputs)

In [17]:
loss = MSE(preds, targets)
print(loss)

tensor(2934.0601, grad_fn=<DivBackward0>)


In [18]:
# Training
n = 400
for i in range(n):
  preds = model(inputs)
  loss = MSE(preds, targets)
  loss.backward()
  with torch.no_grad(): # no_grad to disable gradient calculation
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5

  w.grad.zero_() # to clear the previous gradient values
  b.grad.zero_()

  print(f"EPOCHS: {i}/{n}---------Loss: {loss}")

EPOCHS: 0/400---------Loss: 2934.06005859375
EPOCHS: 1/400---------Loss: 1905.5367431640625
EPOCHS: 2/400---------Loss: 1629.979736328125
EPOCHS: 3/400---------Loss: 1419.6165771484375
EPOCHS: 4/400---------Loss: 1258.905517578125
EPOCHS: 5/400---------Loss: 1136.0096435546875
EPOCHS: 6/400---------Loss: 1041.9146728515625
EPOCHS: 7/400---------Loss: 969.7557373046875
EPOCHS: 8/400---------Loss: 914.3048706054688
EPOCHS: 9/400---------Loss: 871.5807495117188
EPOCHS: 10/400---------Loss: 838.5510864257812
EPOCHS: 11/400---------Loss: 812.9070434570312
EPOCHS: 12/400---------Loss: 792.8897705078125
EPOCHS: 13/400---------Loss: 777.1604614257812
EPOCHS: 14/400---------Loss: 764.6987915039062
EPOCHS: 15/400---------Loss: 754.7279052734375
EPOCHS: 16/400---------Loss: 746.6564331054688
EPOCHS: 17/400---------Loss: 740.0343627929688
EPOCHS: 18/400---------Loss: 734.517822265625
EPOCHS: 19/400---------Loss: 729.8458251953125
EPOCHS: 20/400---------Loss: 725.8192138671875
EPOCHS: 21/400-------

In [19]:
preds = model(inputs)
preds

tensor([[ 39.8369,  64.1509],
        [ 55.8679,  45.4663],
        [ 81.7229,  74.5094],
        [ 28.0953,  58.2042],
        [110.9677,  75.2111]], grad_fn=<AddBackward0>)

In [20]:
targets

tensor([[ 32.,  66.],
        [ 52.,  76.],
        [102.,  55.],
        [ 32.,  26.],
        [ 99., 100.]])

# Using Torch built in function


In [21]:
# Using Torch built in function
import torch.nn as nn
import numpy as np


In [22]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43],
                   [91, 88, 64],
                   [87, 134, 58],
                   [102, 43, 37],
                   [69, 96, 70],
                   [74, 66, 43],
                   [91, 87, 65],
                   [88, 134, 59],
                   [101, 44, 37],
                   [68, 96, 71],
                   [73, 66, 44],
                   [92, 87, 64],
                   [87, 135, 57],
                   [103, 43, 36],
                   [68, 97, 70]],
                  dtype='float32')

# Targets (apples, oranges)
targets = np.array([[56, 70],
                    [81, 101],
                    [119, 133],
                    [22, 37],
                    [103, 119],
                    [57, 69],
                    [80, 102],
                    [118, 132],
                    [21, 38],
                    [104, 118],
                    [57, 69],
                    [82, 100],
                    [118, 134],
                    [20, 38],
                    [102, 120]],
                   dtype='float32')

inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)


In [23]:
inputs

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 74.,  66.,  43.],
        [ 91.,  87.,  65.],
        [ 88., 134.,  59.],
        [101.,  44.,  37.],
        [ 68.,  96.,  71.],
        [ 73.,  66.,  44.],
        [ 92.,  87.,  64.],
        [ 87., 135.,  57.],
        [103.,  43.,  36.],
        [ 68.,  97.,  70.]])

We are using 15 training examples to illustrate how to work with large datasets in small batches.

# Dataset and DataLoader
We'll create a TensorDataset, which allows access to rows from inputs and targets as tuples, and provides standard APIs for working with many different types of datasets in PyTorch.

In [24]:
from torch.utils.data import TensorDataset

In [25]:
# Define dataset
train_ds = TensorDataset(inputs, targets)
train_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]),
 tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

The TensorDataset allows us to access a small section of the training data using the array indexing notation ([0:3] in the above code). It returns a tuple with two elements. The first element contains the input variables for the selected rows, and the second contains the targets.

We'll also create a DataLoader, which can split the data into batches of a predefined size while training. It also provides other utilities like shuffling and random sampling of the data.

In [26]:
from torch.utils.data import DataLoader

In [27]:
# Define data loader
batch_size = 5
train_dl = DataLoader(train_ds, batch_size, shuffle=True)

We can use the data loader in a for loop. Let's look at an example.

In [28]:
for xb, yb in train_dl:
    print(xb)
    print(yb)
    break

tensor([[101.,  44.,  37.],
        [ 68.,  96.,  71.],
        [ 69.,  96.,  70.],
        [102.,  43.,  37.],
        [ 68.,  97.,  70.]])
tensor([[ 21.,  38.],
        [104., 118.],
        [103., 119.],
        [ 22.,  37.],
        [102., 120.]])


In each iteration, the data loader returns one batch of data with the given batch size. If shuffle is set to True, it shuffles the training data before creating batches. Shuffling helps randomize the input to the optimization algorithm, leading to a faster reduction in the loss.

#nn.Linear
Instead of initializing the weights & biases manually, we can define the model using the nn.Linear class from PyTorch, which does it automatically.

In [29]:
#nn.Linear
# Define model
model = nn.Linear(3, 2) # 3 features 2 outputs
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[-0.2414,  0.2400, -0.5716],
        [-0.2486, -0.1453, -0.1655]], requires_grad=True)
Parameter containing:
tensor([0.0337, 0.1024], requires_grad=True)


PyTorch models also have a helpful .parameters method, which returns a list containing all the weights and bias matrices present in the model. For our linear regression model, we have one weight matrix and one bias matrix.

In [30]:
# Parameters
list(model.parameters())

[Parameter containing:
 tensor([[-0.2414,  0.2400, -0.5716],
         [-0.2486, -0.1453, -0.1655]], requires_grad=True),
 Parameter containing:
 tensor([0.0337, 0.1024], requires_grad=True)]

In [31]:
# Generate predictions
preds = model(inputs)
preds

tensor([[-26.0878, -34.8921],
        [-37.3964, -45.8925],
        [-21.9617, -50.5878],
        [-35.4197, -37.6205],
        [-33.5944, -42.5795],
        [-26.5693, -34.9954],
        [-38.2079, -45.9127],
        [-22.7747, -51.0019],
        [-34.9382, -37.5172],
        [-33.9245, -42.4965],
        [-26.8994, -34.9123],
        [-37.8778, -45.9957],
        [-21.1501, -50.5676],
        [-35.0895, -37.7036],
        [-33.1129, -42.4763]], grad_fn=<AddmmBackward0>)

Loss Function
Instead of defining a loss function manually, we can use the built-in loss function mse_loss.

In [32]:
import torch.nn.functional as F

The nn.functional package contains many useful loss functions and several other utilities.

In [33]:
# Define loss function
loss_fn = F.mse_loss

In [34]:
loss = loss_fn(model(inputs), targets)
print(loss)

tensor(16049.4512, grad_fn=<MseLossBackward0>)


#Optimizer
Instead of manually manipulating the model's weights & biases using gradients, we can use the optimizer optim.SGD. SGD is short for "stochastic gradient descent". The term stochastic indicates that samples are selected in random batches instead of as a single group.

In [35]:
# optimizer
opt = torch.optim.SGD(model.parameters(), lr = 1e-5)

Note that model.parameters() is passed as an argument to optim.SGD so that the optimizer knows which matrices should be modified during the update step. Also, we can specify a learning rate that controls the amount by which the parameters are modified.

# Train the model
We are now ready to train the model. We'll follow the same process to implement gradient descent:

1. Generate predictions

2. Calculate the loss

3. Compute gradients w.r.t the weights and biases

4. Adjust the weights by subtracting a small quantity proportional to the gradient

5. Reset the gradients to zero

The only change is that we'll work batches of data instead of processing the entire training data in every iteration. Let's define a utility function fit that trains the model for a given number of epochs.

In [36]:
# Utility function to train the model
def fit(num_epochs, model, loss_fn, opt, train_dl):

  # Repeat for given number of epochs
  for epoch in range(num_epochs):

    #train with batches of data
    for xb,yb in train_dl:

      #1. Generate predictions
      pred = model(xb)

      #2. Calculate loss
      loss = loss_fn(pred, yb)

      #3. Compute gradients
      loss.backward()

      #4. Update parameters using  gradients
      opt.step()

      #5. Reset the gradients to zero
      opt.zero_grad()

    # Print the progress
    if (epoch+1) % 10 == 0:
        print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epochs, loss.item()))

Some things to note above:

* We use the data loader defined earlier to get batches of data for every iteration.

* Instead of updating parameters (weights and biases) manually, we use opt.step to perform the update and opt.zero_grad to reset the gradients to zero.

* We've also added a log statement that prints the loss from the last batch of data for every 10th epoch to track training progress. loss.item returns the actual value stored in the loss tensor.

Let's train the model for 100 epochs.

In [37]:
fit(100, model, loss_fn, opt, train_dl)

Epoch [10/100], Loss: 360.1072
Epoch [20/100], Loss: 89.0761
Epoch [30/100], Loss: 277.6465
Epoch [40/100], Loss: 162.6654
Epoch [50/100], Loss: 103.6954
Epoch [60/100], Loss: 84.9424
Epoch [70/100], Loss: 92.9008
Epoch [80/100], Loss: 40.3582
Epoch [90/100], Loss: 67.7592
Epoch [100/100], Loss: 89.8794


Let's generate predictions using our model and verify that they're close to our targets.



In [38]:
# Generate predictions
preds = model(inputs)
preds

tensor([[ 58.5905,  71.7957],
        [ 78.1540,  98.2699],
        [126.7458, 136.9998],
        [ 27.9296,  44.4373],
        [ 90.7992, 110.5816],
        [ 57.3616,  70.7939],
        [ 77.1504,  97.8388],
        [126.6053, 137.3522],
        [ 29.1584,  45.4391],
        [ 91.0245, 111.1523],
        [ 57.5868,  71.3646],
        [ 76.9251,  97.2681],
        [127.7494, 137.4309],
        [ 27.7043,  43.8666],
        [ 92.0281, 111.5834]], grad_fn=<AddmmBackward0>)

In [39]:
# Compare with targets
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 57.,  69.],
        [ 80., 102.],
        [118., 132.],
        [ 21.,  38.],
        [104., 118.],
        [ 57.,  69.],
        [ 82., 100.],
        [118., 134.],
        [ 20.,  38.],
        [102., 120.]])

Indeed, the predictions are quite close to our targets. We have a trained a reasonably good model to predict crop yields for apples and oranges by looking at the average temperature, rainfall, and humidity in a region. We can use it to make predictions of crop yields for new regions by passing a batch containing a single row of input.

In [40]:
model(torch.tensor([[75, 63, 44.]]))

tensor([[54.0832, 68.4683]], grad_fn=<AddmmBackward0>)

The predicted yield of apples is 54.3 tons per hectare, and that of oranges is 68.3 tons per hectare.