<a href="https://colab.research.google.com/github/Somesh140/Pytorch-basics/blob/main/codebase/Pytorchbasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch

In [3]:
# Tensors
t1=torch.tensor(4.)
t1

tensor(4.)

In [4]:
t1.dtype

torch.float32

In [5]:
#Vector
t2 = torch.tensor([1.,2.,4.,6.])
t2

tensor([1., 2., 4., 6.])

In [6]:
t2.dtype

torch.float32

In [7]:
# Matrix
t3 = torch.tensor(
    [
        [4., 5., 6.],
        [9., 59., 9.]
    ]
)

t3

tensor([[ 4.,  5.,  6.],
        [ 9., 59.,  9.]])

In [8]:
# 3- dim tensors
t4 = torch.tensor([
    [
      [ 11.,23., 45.],
      [55,77,88]],

    [[23,434,56],
     [34,56,45]]
])
t4

tensor([[[ 11.,  23.,  45.],
         [ 55.,  77.,  88.]],

        [[ 23., 434.,  56.],
         [ 34.,  56.,  45.]]])

In [9]:
t4.dtype

torch.float32

In [10]:
print(t1)
t1.shape

tensor(4.)


torch.Size([])

In [11]:
print(t2)
t2.shape

tensor([1., 2., 4., 6.])


torch.Size([4])

In [12]:
print(t3)
t3.shape

tensor([[ 4.,  5.,  6.],
        [ 9., 59.,  9.]])


torch.Size([2, 3])

In [13]:
print(t4)
t4.shape

tensor([[[ 11.,  23.,  45.],
         [ 55.,  77.,  88.]],

        [[ 23., 434.,  56.],
         [ 34.,  56.,  45.]]])


torch.Size([2, 2, 3])

In [14]:
# Matrix
t33 = torch.tensor(
    [
        [4., 5., 6.],
        [9., 59.]
    ]
)

t33

ValueError: ignored

In [15]:
# tensor operations
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)

In [16]:
x, w, b

(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

In [17]:
# Arithematic
y = w*x + b
y

tensor(17., grad_fn=<AddBackward0>)

In [18]:
y.backward()

In [19]:
print('dy/dx:', x.grad)
print('dy/dw:', w.grad)
print('dy/db:', b.grad)

dy/dx: None
dy/dw: tensor(3.)
dy/db: tensor(1.)


In [20]:
# Tensor Functions
t6 = torch.full((3,3),77)

In [21]:
t6

tensor([[77, 77, 77],
        [77, 77, 77],
        [77, 77, 77]])

In [22]:
t7 = torch.cat((t3,t6))
t7

tensor([[ 4.,  5.,  6.],
        [ 9., 59.,  9.],
        [77., 77., 77.],
        [77., 77., 77.],
        [77., 77., 77.]])

In [23]:
t8 = torch.sin(t7)
t8

tensor([[-0.7568, -0.9589, -0.2794],
        [ 0.4121,  0.6367,  0.4121],
        [ 0.9995,  0.9995,  0.9995],
        [ 0.9995,  0.9995,  0.9995],
        [ 0.9995,  0.9995,  0.9995]])

In [24]:
t9 = t8.reshape((3,5,-1))
t9

tensor([[[-0.7568],
         [-0.9589],
         [-0.2794],
         [ 0.4121],
         [ 0.6367]],

        [[ 0.4121],
         [ 0.9995],
         [ 0.9995],
         [ 0.9995],
         [ 0.9995]],

        [[ 0.9995],
         [ 0.9995],
         [ 0.9995],
         [ 0.9995],
         [ 0.9995]]])

In [26]:
#Interoperability of numpy
import numpy as np
x= np.array([[1,3],[4,5]])
x

array([[1, 3],
       [4, 5]])

In [28]:
y = torch.from_numpy(x)
y

tensor([[1, 3],
        [4, 5]])